default: &default
  run_jobs_inline: false
  workers:
    '*' : 1
  polling_interval: 5

development:
  <<: *default
  polling_interval: 3 # More frequent polling interval in development environment

test:
  <<: *default
  run_jobs_inline: true

production:
  <<: *default
  workers:
    '*' : 1
    'high' : 3
    'medium,low' : 1
